name: Deploy to test

on:
  push:

jobs:
  deploy-test:
    name: Call reusable workflow when pull request is created
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@main
    with:
      app_name: rabbitmq
      environment: test
      cluster: digdir-fdk-test
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
